version: '3.7'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-atividadecloud
    environment:
      SA_PASSWORD: 'password@Password'
      ACCEPT_EULA: 'Y'
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata-atividadecloud:/var/opt/mssql
    networks:
      - sqlserver_network

app:
  build: .
  ports:
    - "3000:3000"
  depends_on:
    sqlserver:
      condition: service_healthy
  environment:
    DB_SERVER: sqlserver
    DB_USER: sa
    DB_PASSWORD: 'password@Password'
    DB_NAME: data-base
    DB_PORT: 1433
  networks:
    - sqlserver_network


volumes:
  sqlserverdata-atividadecloud:
